# Generated by Django 6.0 on 2025-12-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_activity_content_content_user_alter_activity_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('RE', 'read'), ('WA', 'watched'), ('LI', 'listened'), ('ST', 'studied'), ('OT', 'other')], default='OT', max_length=2),
        ),
    ]
